# Generated by Django 3.2.9 on 2021-12-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_customuser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='deleteme',
            field=models.TextField(default='fubar', max_length=20, null=True),
        ),
    ]
