# Generated by Django 3.2.9 on 2021-12-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_profile_deleteme'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='another',
            field=models.TextField(default='fubar2', max_length=20, null=True),
        ),
    ]
