# Generated by Django 3.2.9 on 2021-12-07 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_profile_another'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='another',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='deleteme',
        ),
    ]
