# Generated by Django 3.2.9 on 2021-12-07 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20211207_0208'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='responsible_teachers',
            field=models.ManyToManyField(related_name='course_responsible_teacher', through='course.CourseResponsibleTeachers', to='base.Profile'),
        ),
        migrations.CreateModel(
            name='CourseSubscribedStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.profile')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='subscribed_students',
            field=models.ManyToManyField(related_name='course_subscribed_students', through='course.CourseSubscribedStudents', to='base.Profile'),
        ),
    ]
