# Generated by Django 3.2.9 on 2021-12-08 02:21

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('base', '0007_auto_20211207_0208'),
        ('course', '0006_remove_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_created_by', to='base.profile', verbose_name='erstellt von'),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Angepasst am'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='course',
            name='responsible_teachers',
            field=models.ManyToManyField(related_name='course_responsible_teacher', through='course.CourseResponsibleTeachers', to='base.Profile', verbose_name='Verantwortliche Dozenten'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subscribed_students',
            field=models.ManyToManyField(related_name='course_subscribed_students', through='course.CourseSubscribedStudents', to='base.Profile', verbose_name='Eingeschriebene Studenten'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
