# Generated by Django 3.2.9 on 2021-12-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20211208_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='file',
            field=models.FileField(default=None, upload_to='', verbose_name='Aufnahme'),
        ),
    ]
