# Generated by Django 3.2.9 on 2021-12-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_recording_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='description',
            field=models.TextField(max_length=2048, null=True, verbose_name='Beschreibung'),
        ),
    ]
