# Generated by Django 3.2.9 on 2021-12-08 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20211208_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideshow',
            name='description',
        ),
    ]
