# Generated by Django 3.2.9 on 2021-12-09 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_auto_20211209_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='recording_description',
            field=models.TextField(blank=True, max_length=2048, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mpeg', 'webm'])], verbose_name='Beschreibung'),
        ),
    ]
