# Generated by Django 3.2.9 on 2021-12-11 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_alter_recording_recording_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recording_of', to='course.lesson'),
        ),
    ]
