# Generated by Django 3.2.9 on 2021-12-11 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_alter_recording_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson'),
        ),
    ]
